name: Lint and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
        env:
          GOROOT: ""
      - name: Test
        run: go test ./...

      - name: Build
        run: go build